# Generated by Django 4.0.2 on 2022-03-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo_coche', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo_de_coche',
            name='created',
        ),
        migrations.RemoveField(
            model_name='modelo_de_coche',
            name='updated',
        ),
    ]
