# Generated by Django 4.0.2 on 2022-03-18 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo_coche', '0002_remove_modelo_de_coche_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo_de_coche',
            name='marca',
        ),
    ]
