# Generated by Django 4.0.2 on 2022-03-16 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marca_coche', '0001_initial'),
        ('modelo_coche', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca_coche',
            name='modelo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelo_de_coche', to='modelo_coche.modelo_de_coche'),
        ),
    ]
