# Generated by Django 4.0.2 on 2022-03-16 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marca_coche', '0001_initial'),
        ('coche', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coche',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marca_coche.marca_coche'),
        ),
    ]
