# Generated by Django 4.0.2 on 2022-03-18 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo_coche', '0003_remove_modelo_de_coche_marca'),
        ('coche', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coche',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modelo_coche.modelo_de_coche'),
            preserve_default=False,
        ),
    ]
