# Generated by Django 4.0.2 on 2022-03-18 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo_coche', '0003_remove_modelo_de_coche_marca'),
        ('marca_coche', '0003_remove_marca_coche_modelo'),
        ('coche', '0003_coche_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='marca',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='marca_coche.marca_coche'),
        ),
        migrations.AlterField(
            model_name='coche',
            name='modelo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='modelo_coche.modelo_de_coche'),
        ),
    ]
