# Generated by Django 4.0.2 on 2022-03-18 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marca_coche', '0003_remove_marca_coche_modelo'),
        ('coche', '0004_alter_coche_marca_alter_coche_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marca_coche.marca_coche'),
        ),
    ]
